export const MATCHING_WEIGHTS = {
  BODY_SHAPE: 30,
  SKIN_TONE: 20,
  STYLE: 15,
  SEASON: 10,
  COLOR: 15,
  FIT: 10,
};

export const MAX_SCORE = 
  MATCHING_WEIGHTS.BODY_SHAPE +
  MATCHING_WEIGHTS.SKIN_TONE +
  MATCHING_WEIGHTS.STYLE +
  MATCHING_WEIGHTS.SEASON +
  MATCHING_WEIGHTS.COLOR +
  MATCHING_WEIGHTS.FIT; // Should be 100
